[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:edge"
pre-build = [
    "dpkg --add-architecture armhf && apt update && apt -y install libudev-dev:armhf libxkbcommon-dev:armhf libinput-dev:armhf libgbm-dev:armhf",
]
